### ISSUE TITLE
[bug] Smarty Syntax error in template

### ISSUE THREAD

**Issue by maciar2000** [bluepayment-plugin/prestashop-plugin-1.7#2]
Wersja PrestaShop: 1.7.2.0
Wersja PHP: 7.1.33
Wersja BluePayment: 2.7.5.1

Podczas wejścia do konfiguracji modułu występuje błąd:
`Syntax error in template "/var/www/xxxx/modules/bluepayment/views/templates/admin/_configure/helpers/form/configure_fields.tpl" on line 24 "{include file="$desc_template"}" variable template file names not allow within {block} tags`

![Zrzut ekranu z 2022-06-09 11-17-00](https://user-images.githubusercontent.com/43175335/172873213-79aca2c1-a68d-485a-afb5-ba1686bc3460.png)

**Comment by coalacode-com** [comment]
fixed
