### ISSUE TITLE
Brak aktualizacji statusu w tabeli ps_order_history

### ISSUE THREAD

**Issue by dominikadamiak** [bluepayment-plugin/prestashop-plugin-1.7#7]
Brak aktualizacji statusu w tabeli ps_order_history przez moduł Płatności Blue Media. Powoduje to rozbieżności w statusach zamówień widocznych w panelu administracyjnym i panelu klienta. Skrypt prawdopodobnie zatrzymuje się podczas wykonywania i prestashop również nie generuje faktury do zamówienia.

Błąd występuje w funkcji updateOrderPayments, w logach sklepu pojawia się błąd Blue Media - Save orderPayment error -- no OrderPayment

PrestaShop 1.7.8.8
PHP: 7.3.33
Wersja modułu: v2.8.5

**Comment by BlueMediaDev** [comment]
Dziękujemy za zgłoszenie. 
W ostatnim czasie wdrażaliśmy poprawki związane z ps_order_history.  Błąd, który jest tutaj wskazany nie jest związany, ze zmianą statusu tylko z ustawieniem płatności. Błąd ten również został w ostatnim czasie poprawiony. Zachęcamy do pobrania aktualnej wersji modułu.

**Comment by dominikadamiak** [comment]
Aktualnie moduł działa prawidłowo. Dziękuję
