### ISSUE TITLE
Sugestie

### ISSUE THREAD

**Issue by kpodemski** [bluepayment-plugin/prestashop-plugin-1.7#9]
Kilka sugestii:

- [ ] wczytujecie gtaga gdy nie jest to potrzebne, https://github.com/bluepayment-plugin/prestashop-plugin-1.7/blob/master/views/templates/hook/gtag.tpl#L18 to nie odpowiedzialnością modułu płatności powinno być wysyłanie transakcji
- [ ] można czytać logi, https://github.com/bluepayment-plugin/prestashop-plugin-1.7/blob/master/bluepayment.php#L429 - wysłałem Wam PR, który to naprawia
- [ ] dlaczego blokować moduł gdy jest wyłączony, a co gdy chcę go najpierw skonfigurować? :) https://github.com/bluepayment-plugin/prestashop-plugin-1.7/blob/master/controllers/admin/AdminBluepaymentPaymentsController.php#L31

**Comment by BlueMediaDev** [comment]
Dziękujemy za sugestie. Tak jak informowaliśmy mailowo prace nad zgłoszonymi kwestiami są realizowane. W tej chwili zamykamy ostatnią z nich związaną z gtga. Wszystkie trzy tematy będą rozwiązane w następnej aktualizacji, o której jeszcze poinformujemy.
